-- Seed: 10 equipamentos para o almoxarifado do departamento de informática
INSERT INTO equipments (id, name, description, tags, created_at, updated_at) VALUES
  ('NB-001', 'Notebook Dell Latitude 5540', 'Notebook corporativo com processador Intel Core i7 13ª geração, 16GB RAM, SSD 512GB. Utilizado pela equipe de desenvolvimento.', ARRAY['notebook', 'dell', 'desenvolvimento'], NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
  ('NB-002', 'Notebook Lenovo ThinkPad T14', 'Notebook Lenovo ThinkPad com tela 14 polegadas, 16GB RAM, SSD 256GB. Designado para analistas de suporte.', ARRAY['notebook', 'lenovo', 'suporte'], NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
  ('MON-001', 'Monitor LG UltraWide 29"', 'Monitor ultrawide 29 polegadas, resolução 2560x1080, painel IPS. Ideal para produtividade e multitarefa.', ARRAY['monitor', 'lg', 'ultrawide'], NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days'),
  ('MON-002', 'Monitor Samsung 24" Full HD', 'Monitor Samsung 24 polegadas Full HD, painel VA, tempo de resposta 5ms. Uso geral no escritório.', ARRAY['monitor', 'samsung'], NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
  ('SRV-001', 'Servidor Dell PowerEdge R750', 'Servidor rack 2U com dois processadores Xeon Gold, 128GB RAM ECC, RAID 10 com 4x SSD 960GB. Hospeda aplicações internas.', ARRAY['servidor', 'dell', 'rack', 'datacenter'], NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
  ('SW-001', 'Switch Cisco Catalyst 9200L', 'Switch gerenciável 24 portas Gigabit Ethernet com 4 portas SFP+ 10G. Instalado no rack principal do CPD.', ARRAY['switch', 'cisco', 'rede', 'datacenter'], NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
  ('IMP-001', 'Impressora HP LaserJet Pro M404dn', 'Impressora laser monocromática com duplex automático e rede Ethernet. Compartilhada entre os setores administrativos.', ARRAY['impressora', 'hp', 'laser'], NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
  ('TEC-001', 'Teclado Logitech MX Keys', 'Teclado sem fio Bluetooth com retroiluminação e recarga USB-C. Compatível com até 3 dispositivos simultaneamente.', ARRAY['teclado', 'logitech', 'periferico'], NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
  ('MOU-001', 'Mouse Logitech MX Master 3S', 'Mouse ergonômico sem fio com sensor 8000 DPI, rolagem MagSpeed e conexão Bluetooth ou receptor USB. Uso diário da equipe.', ARRAY['mouse', 'logitech', 'periferico'], NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
  ('HD-001', 'HD Externo Seagate Backup Plus 2TB', 'Disco rígido externo USB 3.0 de 2TB para backup de projetos e documentos. Armazenado no cofre do CPD.', ARRAY['armazenamento', 'seagate', 'backup', 'externo'], NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days')
ON CONFLICT (id) DO NOTHING;
